Notify error in watch mode
alps-asd/app-state-diagram pull request #134
Opened 2021-11-25 16:11 UTC by koriym

Closes #131 

![image](https://user-images.githubusercontent.com/529021/143474032-0364c7e6-1743-41e8-babd-b394f1f507da.png)

2021-11-25 16:30 UTC, NaokiTsuchiya requested changes

2021-11-25 16:30 UTC, NaokiTsuchiya commented on bin/asd
> +    $msg = sprintf("asd: %s(%s)",$shorName, $e->getMessage());
```suggestion
    $shortName = (new \ReflectionClass($e))->getShortName();
    $msg = sprintf("asd: %s(%s)",$shortName, $e->getMessage());
```

2021-11-25 16:43 UTC, NaokiTsuchiya approved these changes

2021-11-26 00:35 UTC, koriym commented
![image](https://user-images.githubusercontent.com/529021/143510612-124fe528-13a7-4695-af93-c1c8a0dce118.png)

短くしました。

2021-11-26 00:49 UTC, koriym commented
https://app.codecov.io/gh/alps-asd/app-state-diagram

2021-11-26 00:51 UTC, koriym commented
@NaokiTsuchiya codecovにもアクセスできるはずです。

> Codecov uses GitHub permissions to authenticate users. No setup necessary.
Ask your team members to login to Codecov and they will have read/write access to the appropriate repositories.

2021-11-26 01:34 UTC, NaokiTsuchiya reviewed
通知の表示が短くなったのは特に変更はない感じですかね？

2021-11-26 01:49 UTC, koriym commented
@NaokiTsuchiya そうです！

2021-11-26 01:51 UTC, merged

2021-11-26 01:52 UTC, koriym commented
Thanks for the feedback Fujita-san@Mercari!